// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhg5XoOgUMvRzkH4Z_yz4cwfIp7ugEfcc',
    appId: '1:141566722277:web:7803a1a1d14b1eabb1140c',
    messagingSenderId: '141566722277',
    projectId: 'hirlane-996c4',
    authDomain: 'hirlane-996c4.firebaseapp.com',
    storageBucket: 'hirlane-996c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-VeO1ipBtFN_q2tCj1rU917STH_7JXVQ',
    appId: '1:141566722277:android:b485754e946d65f5b1140c',
    messagingSenderId: '141566722277',
    projectId: 'hirlane-996c4',
    storageBucket: 'hirlane-996c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcjoYbylCUDTF2v3ofYYPtdMFY36fJQuc',
    appId: '1:141566722277:ios:1c69c385c00c0a95b1140c',
    messagingSenderId: '141566722277',
    projectId: 'hirlane-996c4',
    storageBucket: 'hirlane-996c4.firebasestorage.app',
    iosBundleId: 'com.example.hirelane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcjoYbylCUDTF2v3ofYYPtdMFY36fJQuc',
    appId: '1:141566722277:ios:1c69c385c00c0a95b1140c',
    messagingSenderId: '141566722277',
    projectId: 'hirlane-996c4',
    storageBucket: 'hirlane-996c4.firebasestorage.app',
    iosBundleId: 'com.example.hirelane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhg5XoOgUMvRzkH4Z_yz4cwfIp7ugEfcc',
    appId: '1:141566722277:web:c1eeab1822c58da1b1140c',
    messagingSenderId: '141566722277',
    projectId: 'hirlane-996c4',
    authDomain: 'hirlane-996c4.firebaseapp.com',
    storageBucket: 'hirlane-996c4.firebasestorage.app',
  );
}
